version: "3"
services:
  mysql:
    container_name: backyard-db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=friends
      - MYSQL_ROOT_PASSWORD=backyard
    ports:
      - "3300:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./backyard-be/DB/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    container_name: backyard-server
    image: amacleanjs/byf_serve
    restart: on-failure
    build: ./backyard-be
    volumes:
      - ./backyard-be:/usr/src/app/server
      - /usr/src/app/server/node_modules
    command: npm run dev
    environment:
      PORT: 5000
      NODE_ENV: dev
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: backyard
      DB_NAME: friends
      DB_PORT: 3306
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  client:
    container_name: backyard-client
    image: amacleanjs/byf_client
    restart: always
    build: ./mapbox-ui
    volumes:
      - ./mapbox-ui:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - "80:3000"
    command: npm start
    environment:
      REACT_APP_ENV: dev
    depends_on:
      - server
volumes:
  db-data:
